### ISSUE TITLE
Está a ir buscar o EventID errado

### ISSUE THREAD

**Issue by marpereira** [Evolve-FTP/swimhub-standalone#3]
linha 156:
int bdIDEventSplit = stroke.equals("MEDLEY") ? getEventDB(splitDistance, "BACK").getID() : getEventDB(splitDistance, "BACK").getID();

certo:
int bdIDEventSplit = stroke.equals("MEDLEY") ? getEventDB(splitDistance, "BACK").getID() : getEventDB(splitDistance, "FREE").getID();

**Comment by jonioliveira** [comment]
Done ;)
